hms_admin/urls.py
from django.urls import path
from . import views

app_name = 'hms_admin'

urlpatterns = [
    path('dashboard',views.admin_home,name='admin_home'),
    path('view_appointments',views.view_appointments,name='appointments'),
    path('view_report/<int:pid>',views.view_report,name='view_report'),
    path('add_doctor',views.add_doctor,name='add_dr'),
    path('doctors list',views.doctors_list,name='view_dr'),
    path('view_patient',views.view_patient,name='view_pt'),
    path('add_department',views.add_department,name='add_dt'),
    path('view_department',views.view_department,name='view_dt'),
    path('change_password',views.chg_pwd,name='chg_pwd'),
    path('admin_login',views.admin_login,name='login'),
    path('add_staff',views.add_staff,name='add_staff'),
    path('view_staff',views.view_staff,name='view_staff'),
    path('consulting-details/<int:dr_id>',views.consultion_details,name='consult_details')

]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment', views.appointments, name='appointment'),
    path('patient_search', views.patient_search, name='patient-search'), 
    path('bookings', views.booking_list, name = 'booking_list'),
    path('profile', views.profile, name="staff-prof"),
    path('view_Prescription',views.view_Prescription,name='view_Prescription'),
     
   
    path('logout',views.logout,name = 'logout')
]

hms_admin/models.py
from django.db import models

# Create your models here.

class AdminLogin(models.Model):
    admin_id = models.CharField(max_length = 50)
    admin_password = models.CharField(max_length = 20)
 
    class Meta :
        db_table = 'admin_tb'


class Department(models.Model):
    department = models.CharField(max_length = 50)
    description = models.CharField(max_length=2000)
    pic = models.ImageField(upload_to = 'department/')

    class Meta :
        db_table = 'dept_tb'



class Doctor(models.Model):
    doctor_name = models.CharField(max_length = 50)
    doctor_email = models.CharField(max_length = 50)
    doctor_contact = models.CharField(max_length = 50)
    department = models.ForeignKey(Department, on_delete = models.CASCADE)
    qualification = models.CharField(max_length = 50)
    experience = models.CharField(max_length = 50)
    fee = models.CharField(max_length = 50)
    pic = models.ImageField(upload_to = 'doctor/')
    username = models.IntegerField()
    password = models.CharField(max_length=50)
    status = models.CharField(max_length=20, default = 'active')
    
    class Meta :
        db_table = 'doctr_tb'


class Staff(models.Model):
    name = models.CharField(max_length = 50)
    mail = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    password = models.CharField(max_length=10)
    pic = models.ImageField(upload_to = 'staff/')
    status = models.CharField(max_length=20, default = 'active')
    
    class Meta :
        db_table = 'staff_tb'

class Consultation(models.Model) : 

    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    day = models.CharField(max_length = 20)
    time = models.CharField(max_length = 20)
    status = models.CharField(max_length = 20, default = 'available')
    
    class Meta :
        db_table = 'consult_tb'

hms_admin/views.py
from django.shortcuts import render,redirect

from common.models import Patient
from patient.models import Booking
from .models import * # we give * to import all model class from models.py
from django.core.mail import send_mail
from random import randint
from django.conf import settings # importing settings.py
from common.auth_guard import auth_admin
# Create your views here.

def admin_login(request):
    msg = ''   # declaring a variable

    if request.method == 'POST':

        user_name = request.POST['admin_id'] # username is variable, admin_id is textbox name in html page.
        password = request.POST['password']
        try: 
            data = AdminLogin.objects.get(admin_id = user_name ,
            admin_password = password)       # model name properties (models) = variablename(views)
            request.session['admin'] = True
            return redirect('hms_admin:admin_home') # redirect to home page

        except Exception as e:
            print(e)
            msg = 'Invalid User Name or Password'  # pass a message

            # we pass data form views to html in dictionary format in render()
    return render(request,'hms_admin/admin_login.html',{'error_msg':msg})   # keyvalue {'error_msg':msg}

@auth_admin
def admin_home(request):
    doctors_count = Doctor.objects.filter(status = 'active').count()
    patients_count = Patient.objects.filter(status = 'active').count()
    department_count = Department.objects.all().count()
    
    return render(request,'hms_admin/admin_home.html',{'doctors_count' : doctors_count,'patients_count': patients_count,'department_count': department_count})

@auth_admin
def chg_pwd(request):
    return render(request,'hms_admin/admin_change_password.html')

@auth_admin
def view_appointments(request):
    appointments = Booking.objects.all()
    return render(request,'hms_admin/view_appointments.html',{'appointments':appointments})

@auth_admin
def add_doctor(request):
    error_msg = ''
    success_msg = ''

    departments = Department.objects.all()  # select * from department
    

    if request.method == 'POST':
        name = request.POST['doctor_name']
        email = request.POST['doctor_email']
        contact = request.POST['doctor_number']
        department = request.POST['doctor_dept']
        qualification = request.POST['qaulification']
        experience = request.POST['experience']
        fee = request.POST['fees']
        pic = request.FILES['doctor_photo']

        user_name = randint(1111,9999) # doctors username will be a unique 4 digit number
        password = 'doc-' + str(user_name) +'-' + contact[6:10]  # eg : password will be doc-3454-john 

        #  username and password will be sent to doctors email
        
        email_exist = Doctor.objects.filter(doctor_email = email).exists()
        if not email_exist:

            new_doctor = Doctor(doctor_name = name, doctor_email = email, doctor_contact = contact,department_id = department,
            qualification = qualification, experience = experience, fee = fee, pic = pic, username = user_name, password = password)
            new_doctor.save()
            success_msg = 'Doctor Added Succesfully'
        else:
            error_msg = 'Email Exists'    


         

        # send_mail(
        #     'username and password',
        #     'Hi, your username is '+ str(user_name) +' and password is ' + password,
        #     settings.EMAIL_HOST_USER,
        #     [email]
        # )
    return render(request,'hms_admin/add_doctor.html', {'departments':departments,'error_message' : error_msg, 'succes_message' : success_msg})

@auth_admin
def consultion_details(request,dr_id):

    consultation_detail = Consultation.objects.filter(doctor = dr_id)
    doctor_name = Doctor.objects.filter(id = dr_id).values('doctor_name')[0]['doctor_name']
    error_msg = ''
    success_msg = ''


    if request.method == 'POST':

        consultaion_day = request.POST['consult_day']
        consultaion_time = request.POST['frm_time'] + ' - ' + request.POST['to_time']
        record_exist = Consultation.objects.filter(doctor = dr_id, day = consultaion_day, time = consultaion_time).exists()
        
        if not record_exist :
            new_record = Consultation(day = consultaion_day, time = consultaion_time, doctor_id = dr_id)
            new_record.save()
            success_msg = 'Record Added Succesfully'

        else:
            error_msg = 'Record Already Added'

    context = {
            'doctor_name': doctor_name,
            'consultation_detail': consultation_detail,
            'error_message' : error_msg,
            'success_message' :success_msg
                }
    return render(request,'hms_admin/consultation.html', context)

@auth_admin
def doctors_list(request):
    doctors = Doctor.objects.filter(status = 'active')
    return render(request,'hms_admin/doctors_list.html',{'active_doctors' : doctors})


@auth_admin
def view_report(request,pid):
    patient = Booking.objects.get(id=pid)
    return render(request,'hms_admin/view_report.html',{'patient':patient})


@auth_admin
def view_patient(request):
    patient = Patient.objects.all()
    return render(request,'hms_admin/view_patient.html',{'patient':patient})

@auth_admin
def add_department(request):
    error_msg = ''
    success_msg =''
    if request.method == 'POST':

        department = request.POST['dept'].lower()
        description = request.POST['desc']
        pic = request.FILES['pic']

        record_exist = Department.objects.filter(department = department).exists() # checking if the dept int table 
        # exist() give boolean result, that is true if data exist
        if not record_exist :

            new_dept = Department(department = department , description = description, pic = pic)
            new_dept.save()
            success_msg = 'Department Added Succesfully'
        else:
            error_msg = 'Department Exist'
            
    return render(request,'hms_admin/add_dept.html' , {'error_message' : error_msg, 'success_message' :success_msg})

@auth_admin
def view_department(request):
    departments = Department.objects.all()
    return render(request,'hms_admin/departments.html', {'departments' :departments})

@auth_admin
def add_staff(request):
    if request.method == 'POST':
        name = request.POST['name']
        mail = request.POST['id']
        address = request.POST['address']
        phone = request.POST['number']
        password = request.POST['pass']
        pic = request.FILES['pic']
        # email_exist =  Staff.objects.filter(mail = mail, status = 'active').exists()
        staff = Staff(name = name, mail = mail,address = address, phone = phone, password = password, pic = pic)
        staff.save()
    return render(request,'hms_admin/add_staff.html')

@auth_admin
def view_staff(request):
    staff = Staff.objects.filter(status = 'active')
    return render(request,'hms_admin/view_staff.html',{'staff':staff})

hms_admin/templates/hms_admin/admin_master.html
{% load static %}
<!-- All other pages extends this page -->

<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

  <title>admin</title>

  <meta name="description" content="" />


  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
    rel="stylesheet" />


  <link rel="stylesheet" href="{% static 'assets/vendor/fonts/boxicons.css' %}" />


  <link rel="stylesheet" href="{% static 'assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
  <link rel="stylesheet" href="{% static 'assets/vendor/css/theme-default.css' %}"
    class="template-customizer-theme-css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />

  <!-- Vendors CSS -->
  <link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

  <link rel="stylesheet" href="{% static 'assets/vendor/libs/apex-charts/apex-charts.css' %}" />

  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/admin-style.css' %}" />
  <script src="{% static 'assets/vendor/js/helpers.js' %}"></script>

  <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
  <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
  <script src="{% static 'assets/js/config.js' %}"></script>


  <style>
    .layout_container{
      margin-top: 50px;
      margin-left: 5%;
      height: 1000px;
      width: 100%;
     
      
    }
    .content-wrapper{
      margin-top: 20px;
    }
    .layout-wrapper{
      background-color: rgb(206, 229, 241);
      width: 100%;
      height: 1200px;
      margin-left: 15px;
    }
   
  </style>


  {% block header %}
  <!-- Add style tag for individual pages  -->
  {% endblock %}


</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">


      <!-- Menu -->
      <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
        <div class="app-brand demo">
          <a href="" class="app-brand-link">
            <span class="app-brand-logo demo" style="margin-bottom: 10px;">
              <svg width="25" viewBox="0 0 25 42" version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                <defs>
                  <path
                    d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                    id="path-1"></path>
                  <path
                    d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                    id="path-3"></path>
                  <path
                    d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                    id="path-4"></path>
                  <path
                    d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                    id="path-5"></path>
                </defs>
                <!-- <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                    <g id="Icon" transform="translate(27.000000, 15.000000)">
                      <g id="Mask" transform="translate(0.000000, 8.000000)">
                        <mask id="mask-2" fill="white">
                          <use xlink:href="#path-1"></use>
                        </mask>
                        <use fill="#696cff" xlink:href="#path-1"></use>
                        <g id="Path-3" mask="url(#mask-2)">
                          <use fill="#696cff" xlink:href="#path-3"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                        </g>
                        <g id="Path-4" mask="url(#mask-2)">
                          <use fill="#696cff" xlink:href="#path-4"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                        </g>
                      </g>
                      <g id="Triangle"
                        transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                        <use fill="#696cff" xlink:href="#path-5"></use>
                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                      </g>
                    </g>
                  </g>
                </g> -->

              </svg>
            </span>

            <div class="avatar avatar-online">
              <img src="{% static 'assets/img/avatars/adminimg.png' %}" alt
                class="h-auto rounded-circle" style="height: 60px; width: 80px;"/>
            </div>
          </a>

          <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
          </a>
        </div>
         
        
        <h4 class="text-dark" style="margin-top: 10px;">Welcome Dr.Fidha</h4>
       

        <div class="menu-inner-shadow"></div>

        <ul class="menu-inner py-1">

          <!-- Dashboard -->
          <li class="menu-item active">
            <a href="{% url 'hms_admin:admin_home' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-home-circle"></i>
              <div data-i18n="Analytics" class="text-dark">Dashboard</div>
            </a>
          </li>

          <li class="menu-header small text-uppercase"><span class="menu-header-text text-dark">Doctor</span></li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:add_dr' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
              <div data-i18n="Authentications" class="text-dark">Add Doctor</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:view_dr' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
              <div data-i18n="Authentications" class="text-dark">View Doctor</div>
            </a>
          </li>

          
          <li class="menu-header small text-uppercase"><span class="menu-header-text text-dark">Staff</span></li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:add_staff' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
              <div data-i18n="Authentications" class="text-dark">Add Staff</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:view_staff' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
              <div data-i18n="Authentications" class="text-dark">View Staff</div>
            </a>
          </li>

          <li class="menu-header small text-uppercase">
            <span class="menu-header-text text-dark">Patients</span>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:view_pt' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-detail"></i>
              <div data-i18n="Form Layouts" class="text-dark">Patient Details</div>
            </a>
          </li>

          <li class="menu-header small text-uppercase">
            <span class="menu-header-text text-dark">Appointment</span>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:appointments' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-dock-top"></i>
              <div data-i18n="Account Settings" class="text-dark">View Appointments</div>
            </a>
          </li>

          <li class="menu-header small text-uppercase">
            <span class="menu-header-text text-dark">Services</span>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:add_dt' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-detail"></i>
              <div data-i18n="Form Elements" class="text-dark">Add Department</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'hms_admin:view_dt' %}" class="menu-link text-decoration-none">
              <i class="menu-icon tf-icons bx bx-detail"></i>
              <div data-i18n="Form Layouts" class="text-dark">View Department</div>
            </a>
          </li>

      
        </ul>

      </aside>
      <!-- Menu -->

      <!-- Layout container -->
      <div class="layout_container">
        <!-- Navbar -->

        <nav
          class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
          id="layout-navbar">
          <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
            <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
              
              <i class="bx bx-menu bx-sm"></i>
            </a>
          </div>
 
          <div class="navbar-nav-right d-flex align-items-center justify-content-end" id="navbar-collapse">
 

            <!-- navbar  -->
            <a href="" class="btn btn-danger"  >Logout</a>


          </div>
        </nav>
        <!-- / Navbar -->



        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->

          <div class="container-xxl flex-grow-1 container-p-y">

            <div class="row">

              <div class="col-md-12">

                {% block content %}

                {% endblock %}

              </div>

            </div>

          </div>
          <!-- / Content -->



          <!-- Footer -->
          <footer class="content-footer footer bg-footer-theme">

          </footer>
          <!-- / Footer -->

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->



  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="{% static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
  <script src="{% static 'assets/vendor/libs/popper/popper.js' %}"></script>
  <script src="{% static 'assets/vendor/js/bootstrap.js' %}"></script>
  <script src="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

  <script src="{% static 'assets/vendor/js/menu.js' %}"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  <script src="{% static 'assets/vendor/libs/apex-charts/apexcharts.js' %}"></script>

  <!-- Main JS -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <!-- Page JS -->
  <script src="{% static 'assets/js/dashboards-analytics.js' %}"></script>

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>

  <script src=" {% static 'assets/js/add_admin.js' %}"></script>
  <script src=" {% static 'assets/js/add_doctor.js' %}"></script>
  <script src=" {% static 'assets/js/add_patient.js' %}"></script>
  <script src=" {% static 'assets/js/home.js' %}"></script>
  <script src=" {% static 'assets/js/home.js' %}"></script>

</body>

</html>

hms_admin/templates/hms_admin/doctors_list.html
{% extends 'hms_admin/admin_master.html' %}
{% load static %}

{% block header %}

<link rel="stylesheet" href=" {% static 'assets/css/view_admin.css' %}">
<style>
    #tb1{
        padding-left:160px;
        
    }
</style>

{% endblock %}

{% block content %}

<section>
    <div class="container-fluid" style="margin:0;">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center mt-5">
                <div>
                    <h2>View Available Doctors</h2>

                    <div class="mt-5" style="width:700px; " id="tb1">


                        <table style="border-spacing: 10px; border:1px solid white;  border-collapse: collapse;" class="table table-striped table-responsive">
                            <thead class="table-dark">
                                <tr>
                                    <th>Sl.NO</th>
                                    <th> Name </th>
                                    <th>Department </th>
                                    <th></th>
                                    <th></th>
                                     
                                </tr>
                            </thead>
                            <tbody>
                                 
                                {% for doctor in active_doctors %}
                                <tr>
                                    <td><a class="text-dark"> {{ forloop.counter }}</a></td>
                                   
                                    <td><a class="text-dark"> {{ doctor.doctor_name | title }}</a></td>
                                   
                                    <td><a class="text-dark"> {{ doctor.department.department }} </a></td>
                                  
                                    <td><a href="" class="btn btn-success">Details</a></td>
                                    <td><a href="{% url 'hms_admin:consult_details' doctor.id %}" class="btn btn-warning">Consultation</a></td>
                                </tr>
                                    
                                {% endfor %}

                        
                            </tbody>
                          </table>


                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

hms_admin/templates/hms_admin/view_appointments.html
{% extends 'hms_admin/admin_master.html' %}
{% load static %}

{% block header %}

<link rel="stylesheet" href=" {% static 'assets/css/view_admin.css' %}">


{% endblock %}

{% block content %}

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center mt-5">
                <div>
                    <h2>View Appointments</h2>

                    <div class="mt-5" style="width:100%;">

                      {% if appointments %}
                        <table class="table table-striped" style="border-spacing: 10px; border:1px solid white;  border-collapse: collapse;">
                            <thead class="table-dark">
                                <tr>
                                    <th> Sl No </th>
                                    <th> Patient Name </th>
                                    <th> Department </th>
                                    <th> Doctor </th>
                                    <th> Date </th>
                                    <th> Time </th>
                                    <th> Action</th>
                                </tr>
                            </thead>
                            {% for appointment in appointments %}
                            <tbody>
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{appointment.patient_name}}</td>
                                    <td>{{appointment.doctor.department.department}}</td>
                                    <td>{{appointment.doctor.doctor_name}}</td>
                                    <td> {{appointment.booking_date}}</td>
                                    <td>{{appointment.time}} </td>
                                    <td>
                                        <a href="{% url 'hms_admin:view_report' appointment.id %}">
                                            <button type="button" class="btn btn-success">
                                                View Report</button></a>
                                    </td>
                                
                                    
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                        {% else %}
                        <h1>No Records</h1>
                        {% endif %}

                        {% comment %}

<!-- 
                        <script>
                            function report() {
                                location.replace("{% url 'hms_admin:view_report' %}")
                            }
                        </script> -->
                        {% endcomment %}


                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}