common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('departments', views.dept, name='depts'),
    path('services', views.service, name='services'),
    path('department/<int:id>', views.department_details, name='department_details'),
    path('doctor/<int:id>', views.doctor_details, name='doctor_details'),
    path('doctor', views.doctor, name='dr'),
    path('user-type', views.user_type, name='user_type'),
    path('login', views.login, name='login'),
    path('register', views.patient_registration, name='pat_register'),
    path('make-appointment',views.make_appointment,name = 'make_appointment'),
    path('forgot_pass',views.forgot_pass,name = 'forgot_pass'),
    path('reset_pass',views.reset_pass,name = 'reset_pass')
]

doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    path('home', views.doctor_home, name='dr_home'), 
    path('profile', views.profile, name='dr_profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('appointment/', views.appointment, name='appointment'),
    path('search/patients',views.search_patients,name='search_patients'),
    path('change_password',views.change_password,name='change_pswd'),
    path('consulting',views.consulting,name='consulting'),
    path('patient/list',views.get_patients,name='get_patients'),
    path('prescription/<int:b_id>',views.add_prescription,name='add_prescription'),
    path('booking/<int:b_id>',views.patient_details,name='patient_details'),
    path('booking-submit',views.submit_prescription,name='submit_prescription'),

    

]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription'),
    path('orderpayment',views.order_payment,name='orderpayment'),
    path('updatepayment',views.updatepayment,name='updatepayment'),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment', views.appointments, name='appointment'),
    path('patient_search', views.patient_search, name='patient-search'), 
    path('bookings', views.booking_list, name = 'booking_list'),
    path('profile', views.profile, name="staff-prof"),
    path('view_Prescription',views.view_Prescription,name='view_Prescription'),
     
   
    path('logout',views.logout,name = 'logout')
]

doctor/models.py
from django.db import models
from hms_admin.models import Doctor
# Create your models here.
 

class Consultion(models.Model) : 

    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    day = models.CharField(max_length = 20)
    time = models.CharField(max_length = 20)

 

doctor/views.py
import json
from django.shortcuts import render, redirect
from hms_admin.models import Doctor
from django.http import JsonResponse
from common.models import Patient
from patient.models import Booking
from datetime import datetime
from .serializers import *
from json import loads
from common.auth_guard import auth_doctor
from datetime import datetime
from datetime import date
import time
# Create your views here.


@auth_doctor
def doctor_home(request):
    doctors = Doctor.objects.get(id=request.session['doctor'])
    doctor = Doctor.objects.filter(
        id=request.session['doctor']).values('doctor_name')
    doc_name = doctor[0]['doctor_name']
    patients_count = Patient.objects.all().count()
   
   
    # today = datetime.strftime(datetime.today(),"%d-%m-%Y")
    today = str(date.today())
     
    total_bookings = Booking.objects.filter(doctor = request.session['doctor'],booking_date = today, status = 'booked').count()
    print('jdwye',total_bookings)
    return render(request, 'doctor/doctor_home.html', {'doc_name': doc_name,'patients_count': patients_count, 'total_bookings' : total_bookings,'doctor': doctors })


def profile(request):
    doctor = Doctor.objects.get(id=request.session['doctor'])
    return render(request, 'doctor/profile.html', {'doctor': doctor})


def edit_profile(request):
    doctor = Doctor.objects.get(id=request.session['doctor'])

    if request.method == 'POST':
        name = request.POST['dr_name']
        email = request.POST['dr_email']
        contact = request.POST['dr_contact']
        qualification = request.POST['dr_qual']
        experience = request.POST['dr_exp']
        fee = request.POST['dr_fee']

        doctor = Doctor.objects.get(id=request.session['doctor'])
        doctor.doctor_name = name
        doctor.doctor_email = email
        doctor.doctor_contact = contact
        doctor.qualification = qualification
        doctor.experience = experience
        doctor.fee = fee
        doctor.save()
        return redirect('doctor:dr_profile')

    return render(request, 'doctor/edit_profile.html', {'doctor': doctor})


def appointment(request):
    doctors = Doctor.objects.get(id=request.session['doctor'])
    # today = datetime.strftime(datetime.today(), "%d/%m/%Y")
    today = str(date.today())
    records = Booking.objects.filter(doctor = request.session['doctor'], status = 'booked',booking_date = today)

    return render(request, 'doctor/appointment.html',{'booking_records' : records,'doctor':doctors})


def search_patients(request):
    patients_list = Patient.objects.all()
    return render(request, 'doctor/search_patients.html', {'patients_list': patients_list})




def change_password(request):
    doctors = Doctor.objects.get(id=request.session['doctor'])

    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_password = request.POST['old_passwd']
        new_password = request.POST['new_passwd']
        confirm_password = request.POST['confirm_passwd']

        if new_password == confirm_password:
            if len(new_password) > 8:
                
                doctor = Doctor.objects.get(id=request.session['doctor'])
                
                if doctor.password == old_password:
                    doctor.password = new_password
                    doctor.save()
                    success_msg = 'Password Changed'
                
                else:
                    error_msg = 'Incorrect Password'

            else:
                error_msg = 'Password Should Be Min 8 Characters'

        else:
            error_msg = 'Password does\'nt match'

    return render(request, 'doctor/change_paswd.html', {'error_msg': error_msg, 'success_msg': success_msg,'doctor':doctors})


def consulting(request):
    return render(request, 'doctor/consulting.html')


def get_patients(request):
    search_text = request.GET['search_text']
    
    search_result = Patient.objects.filter(patient_name__icontains = search_text)

    serialized_set = [{ 'id' : p.id, 'p_name' : p.patient_name.title() }  for p in search_result]
    return JsonResponse({'search_result' : serialized_set})


def patient_details(request,b_id):
    booking_record = Booking.objects.get(id = b_id) 
    
    return render(request,'doctor/patient_details.html', {'booking_record' : booking_record,})

def add_prescription(request,b_id):
    return render(request,'doctor/prescription.html', {'booking_id':b_id})

def submit_prescription(request):

    prescription = request.POST['prescription']
    

    prescription_obj=json.loads(prescription)

    print(prescription_obj[0]['booking'])
    bid=prescription_obj[0]['booking']
    booking=Booking.objects.get(id=bid)
 
    serialized_data = PrescriptionSerializer(data = prescription_obj,many = True)

    if serialized_data.is_valid():
        serialized_data.save()
        booking.status="consulted"
        booking.save()
        Booking.objects.filter(id = bid).update(status = 'completed')


    
    else :
        print('errore')
        print(serialized_data.errors)
    return JsonResponse(serialized_data.data,safe=False)

 

doctor/templates/doctor/doctor_home.html
{% extends 'doctor/doctor_master.html' %}
{% load static %}

{% block header %}
 
<link rel="stylesheet" href=" {% static 'css/cards.css' %}" />

{% endblock %}

{% block content %}

<h1 style="color: rgb(6, 6, 165);  text-align: center;"
class="mb-4">
Welcome Dr.{{ doc_name | title }}
</h1>

<div class="container-xxl flex-grow-1 container-p-y">
 
  <div class="row">
    <div class="col-md-12">
      <div class="card-category-5">
        
        <ul class="all-pr-cards">
          <li>
            <a href="{% url 'doctor:appointment' %}">
             <div class="per-card-3" style="height: 200px;">
                 <div class="card-image">
                     <span></span>
                     <img src="{% static 'assets/img/calendar.png' %}" height="200px" class="logo" />
                   </div>
                 <div class="card-body">
                   <h5 class="card-title">Today's Appointment</h5>
                   <p class="card-text"> Total Booking : {{ total_bookings }}</p>
                   
                    
                 </div>
               </div>

            </a>
            </li>
       
         
            {% comment %} <li>
             <a href="{% url 'patient:booking_history' %}">
             <div class="per-card-3" style="height: 200px;">
                 <div class="card-image">
                     <span></span>
                     <img src="{% static 'assets/img/calendar.png' %}" height="200px" class="logo" />
                   </div>
                 <div class="card-body">
                   <h5 class="card-title">Search Patients</h5>
                   <p class="card-text"> Total Patients : {{ patients_count }}</p>
                  
                   
                    
                 </div>
               </div>
             </a>
            </li> {% endcomment %}
       </ul>

         



      </div>

      <!-- <div class="card-category-5">

        <ul class="all-pr-cards">
          <li>
            <div class="per-card-3">
              <div class="card-image">
                <span></span>
                <img src="{% static 'assets/img/images.png' %}" class="logo" />
              </div>

              <div class="card-content mb-5">
                <span class="per-position"><br /><br />DEPARTMENTS</span>
                <div class="social-icons">
                  <i class="fa-solid fa-7" style="font-style: #fff"><br />0</i>
                </div>
              </div>
            </div>
          </li>

          <li>
            <div class="per-card-3">
              <div class="card-image">
                <span></span>
                <img src="{% static 'images/pt.png' %}" class="logo" />
              </div>

              <div class="card-content mb-5">
                <span class="per-position"><br /><br />PATIENTS LIST</span>
                <div class="social-icons">
                  <i class="fa-solid fa-7" style="font-style: #fff"><br />0</i>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div> -->

    </div>
  </div>
</div>

    <!-- calendar icon  -->
    <script
      src="https://kit.fontawesome.com/a076d05399.js"
      crossorigin="anonymous"
    ></script>

{% endblock %}

doctor/templates/doctor/edit_profile.html
{% extends 'doctor/doctor_master.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href=" {% static 'css/dr_edit_profile.css' %}">
{% endblock %}

{% block content %}

<section class="edit_section">
    
    <div class="container">

        <div class="main-body">

            <!-- Breadcrumb -->
            <!-- <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav> -->
            <!-- /Breadcrumb -->

            <!-- <img src="{% static 'images/team/3.jpg' %}" alt="" class="img-fluid w-100"> -->


            <div class="row mt-1 mb-2 ">
                <div class="col-2"></div>
                <div class="col-8">

                </div>
                <div class="col-2"></div>
            </div>

            <div class="row"></div>

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ doctor.pic.url }}" alt="Admin" class="rounded-circle"
                                    width="150">
                                <div class="mt-3">
                                    <h4>{{ doctor.doctor_name }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <line x1="16" y1="2" x2="16" y2="6"></line>
                                        <line x1="8" y1="2" x2="8" y2="6"></line>
                                        <line x1="3" y1="10" x2="21" y2="10"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:appointment' %}"> Appointments</a> 
                                </h5>

                            </li>
                          
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="8.5" cy="7" r="4"></circle>
                                        <line x1="20" y1="8" x2="20" y2="14"></line>
                                        <line x1="23" y1="11" x2="17" y2="11"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:search_patients' %}"> Patients </a>
                                </h5>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                                        <path d="M7 11V7a5 5 0 0 1 9.9-1"></path>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:change_pswd' %}">Change Password</a> 
                                </h5>
                            </li>
                          
                        </ul>
                    </div>
                </div>

                <div class="col-md-8">
                    <form method="POST">
                        {% csrf_token %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                              
                                <div class="col-sm-3">
                                    <h6 class="mb-0"> Name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" name = 'dr_name' class="form-control" value=" {{ doctor.doctor_name}}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email ID</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" name = 'dr_email' class="form-control" value="{{ doctor.doctor_email}}">
                                </div>                                
                            </div>
                            <hr>
                            
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Contact Number</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name = 'dr_contact' value="{{ doctor.doctor_contact}}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Department</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" readonly class="form-control" value="{{ doctor.department.department }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Qualification</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name = 'dr_qual' value="{{ doctor.qualification }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Experience</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name = 'dr_exp' value="{{ doctor.experience }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Consultancy Fees</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name = 'dr_fee' value="{{ doctor.fee }}">
                                </div>
                            </div>

                            <hr>
                            <div class="row">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-9 text-secondary">
                                    <button  type="submit" class="btn btn-primary px-4" value="Save Changes">Save</button>
                                </div>
                            </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>

</section>


{% endblock %}

doctor/templates/doctor/profile.html
{% extends 'doctor/doctor_master.html' %}

{% load static %}

{% block header %}
<link rel="stylesheet" href=" {% static 'css/dr_profile.css' %}">
{% endblock %}

{% block content %}

<section class="prof_section">

    <div class="container" >

        <div class="main-body">

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ doctor.pic.url }}" alt="Admin" class="rounded-circle"
                                    width="150">
                                <div class="mt-3">
                                    {{ doctor.doctor_name }}
                                    <h4>  </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <line x1="16" y1="2" x2="16" y2="6"></line>
                                        <line x1="8" y1="2" x2="8" y2="6"></line>
                                        <line x1="3" y1="10" x2="21" y2="10"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:appointment' %}"> Appointments</a> 
                                    <!-- <a href="{% url 'doctor:consulting' %}"> Consulting</a>  -->

                                </h5>

                            </li>
                          
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="8.5" cy="7" r="4"></circle>
                                        <line x1="20" y1="8" x2="20" y2="14"></line>
                                        <line x1="23" y1="11" x2="17" y2="11"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:search_patients' %}"> Patients </a> 
                                </h5>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                                        <path d="M7 11V7a5 5 0 0 1 9.9-1"></path>
                                    </svg> &ensp;
                                  <a href="{% url 'doctor:change_pswd' %}">Change Password</a>  
                                </h5>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-8"> 
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Name</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    
                                       {{ doctor.doctor_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Email ID</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.doctor_email }}
                                </div>                                
                            </div>
                            <hr>
                            
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Contact Number</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.doctor_contact }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Department</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.department.department }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Qualification</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.qualification }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Experience</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.experience }}
                                     
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Consultancy Fees</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.fee }}
                                     
                                </div>
                            </div>

                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-primary "  
                                        href="{% url 'doctor:edit_profile' %}">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>


{% endblock %}