common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('departments', views.dept, name='depts'),
    path('services', views.service, name='services'),
    path('department/<int:id>', views.department_details, name='department_details'),
    path('doctor/<int:id>', views.doctor_details, name='doctor_details'),
    path('doctor', views.doctor, name='dr'),
    path('user-type', views.user_type, name='user_type'),
    path('login', views.login, name='login'),
    path('register', views.patient_registration, name='pat_register'),
    path('make-appointment',views.make_appointment,name = 'make_appointment'),
    path('forgot_pass',views.forgot_pass,name = 'forgot_pass'),
    path('reset_pass',views.reset_pass,name = 'reset_pass')
]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription'),
    path('orderpayment',views.order_payment,name='orderpayment'),
    path('updatepayment',views.updatepayment,name='updatepayment'),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment', views.appointments, name='appointment'),
    path('patient_search', views.patient_search, name='patient-search'), 
    path('bookings', views.booking_list, name = 'booking_list'),
    path('profile', views.profile, name="staff-prof"),
    path('view_Prescription',views.view_Prescription,name='view_Prescription'),
     
   
    path('logout',views.logout,name = 'logout')
]

common/models.py
from django.db import models

# Create your models here.

class Patient(models.Model):
    patient_name = models.CharField(max_length = 50)
    email = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    age = models.IntegerField()
    phone = models.BigIntegerField()
    blood_grp = models.CharField(max_length=10)
    dob = models.CharField(max_length=20)
    gender = models.CharField(max_length=10)
    status = models.CharField(max_length=20, default = 'active')
    pic = models.ImageField(upload_to = 'patient/', default = 'patient/default-user.png')

    class Meta :
        db_table = 'patient_tb'

common/views.py
import string
from django.shortcuts import render,redirect,reverse
from hms_admin.models import Staff,Doctor
from .models import Patient
from hms_admin.models import Department
from django.conf import settings
from django.core.mail import send_mail
from hms_admin.models import AdminLogin
# Create your views here.


def index(request):
    return render(request,'common/index.html')

def user_type(request):
    return render(request,'common/user_type.html')    
 
def about(request):
    return render(request,'common/about.html')

def contact(request):
    return render(request,'common/contact.html')

def dept(request):
    departments = Department.objects.all()
     
    return render(request,'common/department.html',{'departments':departments,})

def service(request):
    return render(request,'common/service.html')


def patient_registration(request):

    error_msg = ''
    success_msg = ''
    if request.method == 'POST':

        name = request.POST['pat_name']
        address = request.POST['pat_address']
        age = request.POST['pat_age']
        blood_group = request.POST['blood_grp']
        contact = request.POST['pat_phno']
        dob = request.POST['pat_dob']
        gender = request.POST['gender']
        email = request.POST['pat_email']

        record_exist = Patient.objects.filter(email = email).exists() # checking if the email entereb by the user exists

        if not record_exist :
            # if user uploaded the picture, then the user picture is upload, other wise a dummy image is saved which is saved in static folder 
            if 'pic' in request.FILES : # here pic is the name attribute of fileuploader
                pic = request.FILES['pic']
        
                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender , pic = pic)
                
            else :

                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender )

            
            patient_record.save()
            success_msg = 'Record Added Succesfully'

        else:
            error_msg = 'Email Exists'
    return render(request,'common/patient_register.html', {'success_msg' : success_msg, 'error_msg' : error_msg})

def login(request):

    user_type = request.GET['user'] # getting query string value from url
    msg = ''
    
     

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if user_type ==  'staff':
             
            try :
                staff = Staff.objects.get(mail = username, password = password)

                if staff.status == 'active':

                    request.session['staff'] = staff.id # setting session for staff
                    request.session['pic'] = staff.pic.url
                    return redirect('staff:staff_home')
                else:
                    msg = 'Account Inactive'
            except :
                msg = 'Invalid Username Or Password'

        if user_type == 'doc':
             
            try :
                doctor = Doctor.objects.get(username = username, password = password)
                request.session['doctor'] = doctor.id
                return redirect('doctor:dr_home')
            except :
                msg = 'Invalid Username Or Password'
        
        if user_type == 'patient':
             
            try :
                patient = Patient.objects.get(email = username, phone = password)
                request.session['patient'] = patient.id
                # if not patient.pic.url == 'static/default-user.png':
                #     print('truee')
                request.session['pic'] = patient.pic.url
                # else:
                #     request.session['pic'] = 'static/default-user.png'

                return redirect('patient:home')
      
            except:
                msg = 'Invalid Username Or Password'

        
    return render(request,'common/login.html', {'error_msg' : msg,'user_type':user_type})

def department_details(request,id):
    department = Department.objects.get(id = id)
    doctors = Doctor.objects.filter(department = id)
    return render(request,'common/department_details.html',{ 'department': department,'doctors' : doctors})

def doctor_details(request,id):
    doctor = Doctor.objects.get(id = id)
    return render(request,'common/doctor_details.html',{'doctor': doctor,})

def doctor(request):
    return render(request,'common/hms_doctor.html')


def make_appointment(request):
 
    if 'patient' in request.session:
        return redirect('patient:appointment_1') 

  
    request.session['log'] = True
    return redirect(reverse('common:login') + '?user=patient') 



def forgot_pass(request):
    
    user_type = request.GET.get('user')
    msg=""
    if request.method=='POST':
        email=request.POST['email']
        
        if user_type=='doc':
             user = Doctor.objects.filter(doctor_email= email)               
            
        if user_type=='patient':
            user = Patient.objects.filter(email=email)

        if user_type=='staff' :
            user = Staff.objects.filter(mail=email)

        print('999',user_type)

        if  user.exists():
            print(user[0])
            print(user[0].id)
            uid=user[0].id    
            message="password reset link  http://127.0.0.1:8000/reset_pass?user=" + user_type + "&id=" + str(uid)
            print(message)
            send_mail(
                'password reset',
                message,
                settings.EMAIL_HOST_USER,
                [user[0].email],
                fail_silently=False)
            
            print('succsess')
        else:
            msg="user not exist"


    return render(request,'common/forgot_pass.html',{'error':msg})

    

def reset_pass(request):
    msg=""
    user_type = request.GET.get('user')
    id=int(request.GET.get('id'))
    if request.method=='POST':
        password=request.POST['password']

        if user_type=='doc':
            user = Doctor.objects.get(id=id)     
            
        if user_type=='patient':
            user = Patient.objects.get(id=id)
            
        if user_type=='staff' :
            user = Staff.objects.get(id=id)


        
        user.password = password
        user.save()
        msg="pasword reset successfull"

    return render(request,'common/reset_pass.html',{'msg':msg})

common/templates/common/contact.html
{% extends 'common/common_master.html' %}
{% load static %}

{% block header %}
{% endblock %}


{% block content %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">Contact Us</span>
          <h1 class="text-capitalize mb-5 text-lg">Get in Touch</h1>

          <!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="hp.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">Contact Us</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
</section>
<!-- contact form start -->

<section class="section contact-info pb-0">
    <div class="container">
         <div class="row">
            <div class="col-lg-4 col-sm-6 col-md-6">
                <div class="contact-block mb-4 mb-lg-0">
                    <i class="icofont-live-support"></i>
                    <h5>Call Us</h5>
                     +823-4565-13456
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 col-md-6">
                <div class="contact-block mb-4 mb-lg-0">
                    <i class="icofont-support-faq"></i>
                    <h5>Email Us</h5>
                     contact@mail.com
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 col-md-6">
                <div class="contact-block mb-4 mb-lg-0">
                    <i class="icofont-location-pin"></i>
                    <h5>Location</h5>
                     North Main Street,Brooklyn Australia
                </div>
            </div>
        </div>
    </div>
</section>

<section class="contact-form-wrap section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h2 class="text-md mb-2">Contact us</h2>
                    <div class="divider mx-auto my-4"></div>
                    <p class="mb-5">Laboriosam exercitationem molestias beatae eos pariatur, similique, excepturi mollitia sit perferendis maiores ratione aliquam?</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form id="contact-form" class="contact__form " method="post" action="mail.php">
                 <!-- form message -->
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-success contact__msg" style="display: none" role="alert">
                                Your message was sent successfully.
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <input name="name" id="name" type="text" class="form-control" placeholder="Your Full Name" >
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <input name="email" id="email" type="email" class="form-control" placeholder="Your Email Address">
                            </div>
                        </div>
                         <div class="col-lg-6">
                            <div class="form-group">
                                <input name="subject" id="subject" type="text" class="form-control" placeholder="Your Query Topic">
                            </div>
                        </div>
                         <div class="col-lg-6">
                            <div class="form-group">
                                <input name="phone" id="phone" type="text" class="form-control" placeholder="Your Phone Number">
                            </div>
                        </div>
                    </div>

                    <div class="form-group-2 mb-4">
                        <textarea name="message" id="message" class="form-control" rows="8" placeholder="Your Message"></textarea>
                    </div>

                    <div class="text-center">
                        <input class="btn btn-main btn-round-full" name="submit" type="submit" value="Send Messege"></input>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


 <div class="google-map ">
    <div id="map"></div>
</div>

{% endblock %}

common/templates/common/department-single.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<span class="text-white">Department Details</span>
					<h1 class="text-capitalize mb-5 text-lg">Single Department</h1>

					<!-- <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item"><a href="#" class="text-white-50">Department Details</a></li>
          </ul> -->
				</div>
			</div>
		</div>
	</div>
</section>


<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="department-img">
					<img src="images/service/bg-1.jpg" alt="" class="img-fluid">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-8">
				<div class="department-content mt-5">
					<h3 class="text-md">Medecine and Health</h3>
					<div class="divider my-4"></div>
					<p class="lead">Age forming covered you entered the examine. Blessing scarcely confined her contempt
						wondered shy. Dashwoods contented sportsmen at up no convinced cordially affection.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum recusandae dolor autem laudantium,
						quaerat vel dignissimos. Magnam sint suscipit omnis eaque unde eos aliquam distinctio, quisquam
						iste, itaque possimus . Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet alias
						modi eaque, ratione recusandae cupiditate dolorum repellendus iure eius rerum hic minus ipsa at,
						corporis nesciunt tempore vero voluptas. Tempore.</p>


					<h3 class="mt-5 mb-4">Services features</h3>
					<div class="divider my-4"></div>
					<ul class="list-unstyled department-service">
						<li><i class="icofont-check mr-2"></i>International Drug Database</li>
						<li><i class="icofont-check mr-2"></i>Stretchers and Stretcher Accessories</li>
						<li><i class="icofont-check mr-2"></i>Cushions and Mattresses</li>
						<li><i class="icofont-check mr-2"></i>Cholesterol and lipid tests</li>
						<li><i class="icofont-check mr-2"></i>Critical Care Medicine Specialists</li>
						<li><i class="icofont-check mr-2"></i>Emergency Assistance</li>
					</ul>

					<a href="" class="btn btn-main-2 btn-round-full">Make an Appoinment<i
							class="icofont-simple-right ml-2  "></i></a>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="sidebar-widget schedule-widget mt-5">
					<h5 class="mb-4">Time Schedule</h5>

					<ul class="list-unstyled">
						<li class="d-flex justify-content-between align-items-center">
							<a href="#">Monday - Friday</a>
							<span>9:00 - 17:00</span>
						</li>
						<li class="d-flex justify-content-between align-items-center">
							<a href="#">Saturday</a>
							<span>9:00 - 16:00</span>
						</li>
						<li class="d-flex justify-content-between align-items-center">
							<a href="#">Sunday</a>
							<span>Closed</span>
						</li>
					</ul>

					<div class="sidebar-contatct-info mt-4">
						<p class="mb-0">Need Urgent Help?</p>
						<h3>+23-4565-65768</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

common/templates/common/department.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}

{% endblock %}


{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<h1 class="text-capitalize mb-5 text-lg">Departments</h1>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="section service-2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
			</div>
		</div>

		<div class="row">
			{% for department in departments %}
			<div class="col-lg-4 col-md-6 ">
				<div class="department-block mb-5">
					<a href="{% url 'common:department_details' department.id %}"> <img src="{{ department.pic.url }}"
							alt="" width="350px" height="250px"> </a>
					<div class="content">
 
							<h4 class="mt-4 mb-2 title-color">{{ department.department | title }}</h4>
				 
						<p class="mb-4">{{ department.description }}</p>
						 
					</div>
				</div>
			</div>

			{% endfor %}
		</div>









	</div>
</section>



{% endblock %}

common/templates/common/department_details.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}

<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.css"
  rel="stylesheet"
/>

<script src=" {% static 'js/doctor_cards.js' %}"></script>


<link rel="stylesheet" href="{% static 'css/doctor_cards.css' %}" />

<style>

</style>

<script>

</script>

{% endblock %}

{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<h1 class="text-capitalize mb-5 text-lg">{{ department.department }}</h1>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				
			</div>
		</div>

		<div class="row">
			<div class="col-lg-10">
				<div class="department-content mt-5">
					<h3 class="text-md">Medecine and Health</h3>
					<div class="divider my-4"></div>
					<p class="lead">{{ department.description }}</p>
				</div>
			</div>
		</div>
	</div>

</section>


<section class="section team">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<div class="section-title text-center">
					<h3 class="text-md" style="align-content: left;">Our Doctors</h3>
					<div class="divider mx-auto my-4"></div>
				</div>
			</div>
		</div>

		<div class="row">

			{% for doctor in doctors %}
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="{% url 'common:doctor_details' doctor.id %}" style="text-decoration: none;">
				<div class="team-block mb-5 mb-lg-0">
					<img src="{{ doctor.pic.url }}" alt="" class="img-fluid w-100">

					<div class="content">
						<h4 class="mt-4 mb-0"> {{ doctor.doctor_name | title }} </h4>
						<p> {{ doctor.qualification }} </p>
					</div>
				</div>
			</a>
			</div>

			{% endfor %}

		</div>
	</div>
</section>




{% endblock %}

common/templates/common/doctor_details.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <!-- <span class="text-white">Doctor Details</span> -->
          <h1 class="text-capitalize mb-5 text-lg">{{ doctor.doctor_name | title }}</h1>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section doctor-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6">
				<div class="doctor-img-block">
					<img src="{{ doctor.pic.url }}" alt="" class="img-fluid w-100">

					<div class="info-block mt-4">
						<h4 class="mb-0">{{ doctor.doctor_name | title }}</h4>
						<p>{{ doctor.qualification |  upper }}</p>

						 
					</div>
				</div>
			</div>

			<div class="col-lg-8 col-md-6">
				<div class="doctor-details mt-4 mt-lg-0">
					<h2 class="text-md">About Me</h2>
					<div class="divider my-4"></div>
					 <p>Name : {{ doctor.doctor_name | title }}</p>
					 <p>Email : {{ doctor.doctor_email }} </p>
					 <p>Qualification : {{ doctor.qualification }} </p>
					 <p>Contact : {{ doctor.doctor_contact }} </p>
					 <p>Fee : Rs {{ doctor.fee }}</p>
					 <br>

					<a href="{% url 'common:make_appointment' %}" class="btn btn-main-2 btn-round-full mt-3">Make an Appoinment<i class="icofont-simple-right ml-2  "></i></a>
				</div>
			</div>
		</div>
	</div>
</section>


{% endblock %}

common/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link rel="stylesheet" href=" {% static 'css/login.css' %}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="CSS/jquery.mobile-1.0a4.1.min.css" />
    <script src="JS/jquery-1.5.2.min.js" type="text/javascript" ></script>
    <script src="JS/jquery.mobile-1.0a4.1.min.js" type="text/javascript" ></script>

  </head>

  <body>
    <section class="login">
      <div class="login_box">
        <div class="left">
          <div class="top_link">
            <a href="{% url 'common:index' %}">
              <img
                src="https://drive.google.com/u/0/uc?id=16U__U5dJdaTfNGobB_OpwAJ73vM50rPV&export=download"
                alt=""
              />
              Return home</a
            >
          </div>
 
          <div class="contact">
            
            <form method="POST">
            
              {% csrf_token %}
              <h3>LOGIN</h3>

              <input type="text" required name="username" placeholder="USERNAME" />
              <input type="password" required name = "password" placeholder="PASSWORD" />
           
              <button class="submit">LOGIN</button>
              <p style="color: red;">   {{ error_msg }}</p>
              <span id="span_reg">
                New User ? <a href="{% url 'common:pat_register' %}"> Register </a>
              </span>
              <span id="span_forgot" >
                  <a href="{% url 'common:forgot_pass' %}?user={{user_type}}"> Forgot Password? </a>
              </span>
              
            </form>
           
          </div>
        </div>

        <div class="right">
          <div class="right-text">
            <h2>HOSPITAL</h2>
            <h2>MANAGEMENT SYSTEM</h2>
          </div>
          <div class="right-inductor">
            <img
              src="https://lh3.googleusercontent.com/fife/ABSRlIoGiXn2r0SBm7bjFHea6iCUOyY0N2SrvhNUT-orJfyGNRSMO2vfqar3R-xs5Z4xbeqYwrEMq2FXKGXm-l_H6QAlwCBk9uceKBfG-FjacfftM0WM_aoUC_oxRSXXYspQE3tCMHGvMBlb2K1NAdU6qWv3VAQAPdCo8VwTgdnyWv08CmeZ8hX_6Ty8FzetXYKnfXb0CTEFQOVF4p3R58LksVUd73FU6564OsrJt918LPEwqIPAPQ4dMgiH73sgLXnDndUDCdLSDHMSirr4uUaqbiWQq-X1SNdkh-3jzjhW4keeNt1TgQHSrzW3maYO3ryueQzYoMEhts8MP8HH5gs2NkCar9cr_guunglU7Zqaede4cLFhsCZWBLVHY4cKHgk8SzfH_0Rn3St2AQen9MaiT38L5QXsaq6zFMuGiT8M2Md50eS0JdRTdlWLJApbgAUqI3zltUXce-MaCrDtp_UiI6x3IR4fEZiCo0XDyoAesFjXZg9cIuSsLTiKkSAGzzledJU3crgSHjAIycQN2PH2_dBIa3ibAJLphqq6zLh0qiQn_dHh83ru2y7MgxRU85ithgjdIk3PgplREbW9_PLv5j9juYc1WXFNW9ML80UlTaC9D2rP3i80zESJJY56faKsA5GVCIFiUtc3EewSM_C0bkJSMiobIWiXFz7pMcadgZlweUdjBcjvaepHBe8wou0ZtDM9TKom0hs_nx_AKy0dnXGNWI1qftTjAg=w1920-h979-ft"
              alt=""
            />
          </div>
        </div>
      </div>
    </section>
   
  </body>

  <script>
const queryString = window.location.search;

const urlParams = new URLSearchParams(queryString);
const userType = urlParams.get('user')

console.log(userType)
if(userType != 'patient'){
  console.log('j')
  document.getElementById('span_reg').style.display = 'none'
  document.getElementById('span_forgot').style.display = 'block'

}

  </script>
</html>